# Generated by Django 5.2.6 on 2025-09-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='respondent',
            name='wants_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='respondent',
            name='interests',
            field=models.ManyToManyField(blank=True, to='main_app.interest'),
        ),
    ]
