# Generated by Django 5.2.6 on 2025-09-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_interest_respondent_wants_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='wants_contact',
        ),
    ]
