# Generated by Django 5.2.6 on 2025-09-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_respondent_wants_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='interests',
        ),
    ]
