# Generated by Django 5.2.6 on 2025-09-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_respondent_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='interests',
            field=models.ManyToManyField(blank=True, to='main_app.interest'),
        ),
    ]
