# Generated by Django 5.2.6 on 2025-09-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='respondent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='respondents/'),
        ),
    ]
