# Generated by Django 5.2.6 on 2025-09-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_question_image_respondent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='respondent',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='respondent',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
