# Generated by Django 5.2.6 on 2025-09-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_choice_choice_text_en_choice_choice_text_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='message_en',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='message_fr',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='name_fr',
        ),
    ]
